#!/usr/bin/env node
/**
 * Assemble the publishable mega distribution at `dist/mega/` (decision B of
 * docs/plans/10-packaging-distribution.md §4.2): a self-contained package
 * directory with the prebuilt `lib/` committed to git, so a git dependency
 * (`dsh plugin add git+…&path:/dist/mega`) installs with ZERO build on the
 * target machine — no prepare script, no allowBuilds, no monorepo context.
 *
 * The directory is gitignored as build output; committing it is an explicit
 * release step (plan §4.1: tag the repo, then `dsh plugin add git+…#tag&path:/dist/mega`).
 *
 *   pnpm build        # first: packages/mega/lib/* must exist
 *   node scripts/build-dist.mjs
 */
import { cpSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const src = join(root, 'packages', 'mega')
const dist = join(root, 'dist', 'mega')

rmSync(dist, { recursive: true, force: true })
mkdirSync(dist, { recursive: true })

// The built artifacts: four host entries + the browser bundle (+ maps).
cpSync(join(src, 'lib'), join(dist, 'lib'), { recursive: true })
// The bundle patch: mounting the four rows is THE point of the mega package.
cpSync(join(src, 'cordis.patch.yml'), join(dist, 'cordis.patch.yml'))
// Builtin facai skills (P3 builtin source) + the packaged usage document.
for (const asset of ['skills', 'USAGE.md']) {
  const from = join(src, 'assets', asset)
  if (exists(from)) cpSync(from, join(dist, 'assets', asset), { recursive: true })
}

// The publishable manifest: exports/dsh declarations copied verbatim, but the
// dev-only script/deps sections dropped (target machines never build it).
const manifest = JSON.parse(readFileSync(join(src, 'package.json'), 'utf8'))
const publishable = {
  name: manifest.name,
  description: manifest.description,
  version: manifest.version,
  type: 'module',
  license: 'MIT',
  exports: manifest.exports,
  dsh: manifest.dsh,
  dependencies: manifest.dependencies,
  peerDependencies: manifest.peerDependencies,
  files: ['lib', 'cordis.patch.yml', 'assets', 'package.json'],
}
writeFileSync(join(dist, 'package.json'), JSON.stringify(publishable, null, 2) + '\n')
writeFileSync(
  join(dist, 'README.md'),
  `# @auto-coding/mega — publishable distribution\n\n`
  + `Generated by \`node scripts/build-dist.mjs\` (decision B, plan 10 §4.2). Install with:\n\n`
  + '```sh\n'
  + `dsh plugin --profile web add git+ssh://git@github.com/facai0316/dsh-auto-coding.git#<tag>&path:/dist/mega\n`
  + '```\n\nThis directory is gitignored; commit it explicitly as the release artifact.\n',
)

function exists(p) {
  try { return statSync(p).isDirectory() || statSync(p).isFile() } catch { return false }
}

console.log(`dist/mega assembled: ${dist}`)
